--FUNCION PARA EL INFORME (SOLO LO PUEDE VER EL ADMINISTRADOR)

ALTER FUNCTION FUNC_OBTENER_INFORME()--EN ESTE PROCEDIMIENTO SE CREA EL FORMATO DEL INFORME COMO UN STRING
RETURNS @informe TABLE(
Servicios VARCHAR(3),
Conductores VARCHAR(3),
Vehiculos VARCHAR(3) ,
Reportes VARCHAR(3),
Mantenimientos VARCHAR(3),
Tipos_servicios VARCHAR(3),
Clientes VARCHAR(3),
Ganancias VARCHAR(10),
Gastos VARCHAR(10),
Balance VARCHAR(10),
Insertar VARCHAR(8),
Actualizar VARCHAR(8),
Eliminar VARCHAR(8),
Total VARCHAR(8)
)
AS
BEGIN
	INSERT INTO @informe (Servicios,Conductores,Vehiculos,Reportes,Mantenimientos,Tipos_servicios,Clientes,Ganancias,Gastos,Balance,Insertar,Actualizar,Eliminar,Total)
	VALUES(
	CAST ((SELECT COUNT(*) FROM Servicio)AS VARCHAR(3)),
	CAST ((SELECT COUNT(*) FROM Conductor)AS VARCHAR(3)),
	CAST ((SELECT COUNT(*) FROM Vehiculo)AS VARCHAR(3)),
	CAST ((SELECT COUNT(*) FROM Reporte)AS VARCHAR(3)),
	CAST ((SELECT COUNT(*) FROM Mantenimiento)AS VARCHAR(3)),
	CAST ((SELECT COUNT(*) FROM Tipo_servicios)AS VARCHAR(3)),
	CAST ((SELECT COUNT(*) FROM TB_Cliente)AS VARCHAR(3)),
	CAST ((SELECT SUM(Monto_Total_Servicio) FROM Servicio)AS VARCHAR(10)),
	CAST ((SELECT SUM(Costo) FROM Mantenimiento)AS VARCHAR(10)),
	CAST ((SELECT SUM(Monto_Total_Servicio) FROM Servicio)-(SELECT SUM(Costo) FROM Mantenimiento)AS VARCHAR(10)),
	CAST ((SELECT COUNT(*) FROM TB_Historial WHERE Accion='Insertar')AS VARCHAR(8)),
	CAST ((SELECT COUNT(*) FROM TB_Historial WHERE Accion='Actualizar')AS VARCHAR(8)),
	CAST ((SELECT COUNT(*) FROM TB_Historial WHERE Accion='Eliminar')AS VARCHAR(8)),
	CAST ((SELECT COUNT(*) FROM TB_Historial)AS VARCHAR(8))
	)
	RETURN
END
GO

--FUNCION PARA OBTENER LOS TOTALES EN LAS TABLAS 

CREATE FUNCTION FUNC_TOTALES_EN_TABLAS()
RETURNS @Totales TABLE(
Servicios VARCHAR(3),
Conductores VARCHAR(3),
Vehiculos VARCHAR(3) ,
Reportes VARCHAR(3),
Mantenimientos VARCHAR(3),
Clientes VARCHAR(3)
)
AS
BEGIN
		INSERT INTO @Totales (Servicios,Conductores,Vehiculos,Reportes,Mantenimientos,Clientes)
		VALUES (
		CAST ((SELECT COUNT(*) FROM Servicio) AS VARCHAR(3)),
		CAST((SELECT COUNT(*) FROM Conductor) AS VARCHAR(3)),
		CAST((SELECT COUNT(*) FROM Vehiculo) AS VARCHAR(3)),
		CAST((SELECT COUNT(*) FROM Reporte) AS VARCHAR(3)),
		CAST((SELECT COUNT(*) FROM Mantenimiento) AS VARCHAR(3)),
		CAST((SELECT COUNT(*) FROM TB_Cliente) AS VARCHAR(3))
		)
	RETURN
END
GO

--PROCEDIMIENTO PARA EJECUTAR LA FUNCION
CREATE PROC PROC_TOTALES_EN_TABLAS
AS
BEGIN
	SELECT *FROM dbo.FUNC_TOTALES_EN_TABLAS()
END
GO
--PROCEDIMIENTO PARA EJECUTAR LA FUNCION DE INFORME 
ALTER PROC PROC_OBTENER_INFORME
AS
BEGIN
	SELECT * FROM DBO.FUNC_OBTENER_INFORME()
END

EXEC PROC_OBTENER_INFORME