--PRUEBAS VARIAS A LA BASE DE DATOS
SELECT * FROM Servicio
SELECT * FROM Tipo_servicios
SELECT *FROM Conductor
SELECT * FROM Vehiculo
SELECT *FROM TB_Cliente
SELECT *FROM Reporte
SELECT *FROM Mantenimiento

--RPOBANDO EL REGISTRO DE MANTENIMIENTOS
EXEC PROC_REGISTRAR_MANTENIMIENTO 'G24S14','25',15.00,"11/16/2021",'CAMBIO DE ACEITE','Realizado','',''

--PROBANDO EL REGISTRO DE REPORTES
EXEC PROC_REGISTRAR_REPORTE '245135','BOMBILLO ROTO',"11/8/2021"

--PROBANDO PROCEDIMIENTO DE AGREGAR SERVICIO
EXEC PROC_REGISTRAR_SERVICIO 12,'777-777','9-999-999','G24S14',"11/5/2021","11/9/2021"
--PROBANDO ACTUALIZAR DATOS DE VEHICULO
SELECT *FROM Vehiculo
EXEC PROC_ACTUALIZAR_DATOS_VEHICULO '1001','FG2S','Sedan',2,'95','Verde'

--PROBANDO ACTUALIZACION DE DATOS DE LOS TIPOS DE SERVICIO
SELECT *FROM Tipo_servicios
EXEC PROC_ACTUALIZAR_DATOS_T_SERVICIOS 1,'Transporte de ocasion',48.00,'transporte de ida y vuelta a un evento o paseo'

--PRUEBA DE ACTUALIZACION DE CLIENTES
SELECT *FROM TB_Cliente
EXEC PROC_ACTUALIZAR_DATOS_CLIENTE '4-233-1004','Pedro','Miranda',"10/2/1989",'6665-3053','Veraguas'

--PROBANDO LA ACTUALIZACION DE ESTADO
EXEC PROC_ACTUALIZAR_ESTADO_VEHICULOS	--SE DEBERIA EJECUTAR CADA VEZ QUE SE INICIE LA APP PARA ACTUALIZAR EL ESTADO CON LA FECHA ACTUAL 

--PROBANDO LA ELIMINACION DE CONDUCTOR Y SUS SERVICIOS
EXEC PROC_ELIMINAR_CONDUCTOR '111-111-111'

--PROBANDO LA ELIMINACION DE SERVICIOS POR SU CODIGO
EXEC PROC_ELIMINAR_SERVICIO 30

--PROBANDO LA ELIMINACION DE VEHICULOS
EXEC PROC_ELIMINAR_VEHICULO '1001'

--PROBANDO LA ELIMINACION DE TIPO DE SERVICIO
EXEC PROC_ELIMINAR_TIPO_SERVICIO 3
--PROBANDO LA ELIMINACION DE CLIENTES
EXEC PROC_ELIMINAR_CLIENTE '4-233-1004'

--PROBANDO LA ACTUALIZACION DE SERVICIOS
EXEC PROC_ACTUALIZAR_DATOS_SERVICIO 27,35,'777-777','245135','9-999-999',"2021-12-06","2021-12-10"