--TIPO DE SERVICIO
--REGISTRAR NUEVO TIPO DE SERVICIO
ALTER PROC PROC_REGISTRAR_TIPO_SERVICIO(@Codigo INT, @Nombre VARCHAR(40),@Costo MONEY,@Descripcion VARCHAR(175))
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM Tipo_servicios WHERE Cod_tipo_servicio=@Codigo)
	BEGIN
		BEGIN TRY
			INSERT INTO Tipo_servicios(Cod_tipo_servicio,Nombre_servicio,Costo_servicio,Descripcion_servicio)
			VALUES(@Codigo,@Nombre,@Costo,@Descripcion)
			COMMIT TRAN
		END TRY
		BEGIN CATCH
			RAISERROR('OCURRIO UN ERROR INESPERADO AL INTENTAR REGISTRAR ESTE NUEVO SERVICIO',12,1)
			ROLLBACK
		END CATCH
	END
	ELSE
		RAISERROR('YA EXISTE UN TIPO DE SERVICIO REGISTRADO CON ESTE CODIGO',12,1)
		ROLLBACK
END
GO

--PROCEDIMIENTO PARA ACTUALIZAR DATOS DE LOS TIPOS DE SERVICIO
CREATE PROC PROC_ACTUALIZAR_DATOS_T_SERVICIOS(@Codigo INT, @Nombre VARCHAR(40),@Costo MONEY,@Descripcion VARCHAR(175))
AS
BEGIN
BEGIN TRAN
	IF EXISTS(SELECT *FROM Tipo_servicios WHERE Cod_tipo_servicio=@Codigo)
	BEGIN
		BEGIN TRY
			UPDATE Tipo_servicios SET
			Nombre_servicio=@Nombre,
			Costo_servicio=@Costo,
			Descripcion_servicio=@Descripcion
			WHERE Cod_tipo_servicio=@Codigo
			COMMIT
		END TRY
		BEGIN CATCH
			RAISERROR('ERROR AL INTENTAR ACTUALIZAR LOS DATOS DEL TIPO DE SERVICIO',10,1)
			ROLLBACK
		END CATCH
	END
	ELSE
	BEGIN
		RAISERROR('NO EXISTE EL TIPO DE SERVICIO ASOCIADO AL CODIGO QUE HA INGRESADO',10,1)
		ROLLBACK
	END
END
GO
--PROCEDIMIENTO PARA ELIMINAR TIPOS DE SERVICIO
CREATE PROC PROC_ELIMINAR_TIPO_SERVICIO(@Codigo_Tipo_Servicio INT)
AS
BEGIN
BEGIN TRAN
	IF EXISTS(SELECT * FROM Tipo_servicios WHERE Cod_tipo_servicio=@Codigo_Tipo_Servicio)
	BEGIN
		BEGIN TRY
			DELETE FROM Tipo_servicios WHERE Cod_tipo_servicio=@Codigo_Tipo_Servicio
			COMMIT
		END TRY
		BEGIN CATCH
			PRINT 'ERROR AL INTENTAR ELIMINAR EL TIPO DE SERVICIO SELECCIONADO'
			ROLLBACK
		END CATCH
	END
	ELSE
	BEGIN
		PRINT('EL CODIGO DE TIPO DE SERVICIO SELECCIONADO NO ESTA REGISTRADO EN LA BASE DE DATOS')
		ROLLBACK
	END
END
GO




